### ISSUE TITLE
Minor refactoring on ros2 humble Dockerfile

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/RoboticsInfrastructure#280]
- [ ] Gather some `apt install`
- [ ] Review `.env` file and move some ENV rules to file
- [ ] Review the use of .deb files
- [ ] Sourcing to bashrc
- [ ] COPY instead of cloning RI repo and cp/mv files after
- [ ] check if colcon building is setting env vars
- [ ] colcon building
- [ ] Entrypoint or default cmd

**Comment by pawanw17** [comment]
- [x]  Gather some apt install (merged)
- [x]  Review .env file and move some ENV rules to file (no environment variables required to move)
- [x]  Review the use of .deb files (it is faster to copy than downloading)
- [x]  Sourcing to bashrc (I think we can move the GAZEBO_MODEL_PATH to .env)
```
source /opt/ros/humble/setup.bash
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/ws/install/custom_robots/share
source /usr/share/gazebo/setup.bash
```
- [x]  COPY instead of cloning RI repo and cp/mv files after (not required since Dockerfiles are now removed from RI)
- [x]  check if colcon building is setting env vars (It is)
- [x]  colcon building (Building fine)
- [ ]  Entrypoint or default cmd (on it)
